### PR TITLE
Allow SET to accept values that come in as VARCHAR despite having a different type.

### PR DESCRIPTION
**Pull request by lmwnshn**
This relies on existing binder functionality, so the support is the same as the binder.
Some examples are booleans coming in as strings and timestamps coming in as strings.
This is a quirk of the Postgres parser.

Before:
```
terrier=# set parallel_execution to TRUE;
ERROR:  invalid value for parameter "parallel_execution": "true"
```

After:
```
terrier=# set parallel_execution to TRUE;
SET
```

### CODE REVIEW

**Review by malin1993ml — APPROVED** [review]
LGTM.

**Comment by apavlo** [comment]
Can we add SQL tests for this?

**Comment by mbutrovich** [comment]
> Can we add SQL tests for this?

That's probably a punt until #1188.

**Comment by apavlo** [comment]
At the very least we could test valid/invalid inputs

**Comment by lmwnshn** [comment]
Per the earlier discussion, will open an issue and assign it to whoever implements SHOW. If this passes, it merges.

**Pull request merged**
