### PR TITLE
Fix passing false arguments to testing scripts. Add dry-run functionality.

### LINKED ISSUE #1384: E2E Performance wal_disabled does not actually disable the WAL (and other config-related bugs).
# Bug Report

E2E Performance wal_disabled does not actually disable the WAL.

## Summary

`generate_server_args_str` does not translate `False` arguments faithfully, so any `.config` settings that are set to `False` will actually be ignored and set to whatever the default behavior in `noisepage` is.

This came up because @mbutrovich noticed that the performance of our TPCC numbers in E2E performance was:
`(Faster) tpcc_wal_ramdisk.json  >> tpcc_wal_disabled.json == tpcc.json (Slower)`

i.e., ramdisk faster than no wal is weird.

This probably affects the nightly stuff as well.

## Environment

Anywhere.

## Steps to Reproduce

1. Add this to `db_server.py` at the end of `NoisePageServer.__init__`:
```
        print()
        print("POTATO BANANA", self.server_args)
        print("POTATO DUCK", generate_server_args_str(self.server_args))
        print()
```
2. You should observe:
```
POTATO BANANA {'wal_file_path': 'wal.log', 'connection_thread_count': 32, 'wal_enable': False, 'record_buffer_segment_size': 10000000}
POTATO DUCK --wal_file_path=wal.log --connection_thread_count=32 --wal_enable --record_buffer_segment_size=10000000
```

Notice that the `False` is dropped. This is what gets passed to the `noisepage` binary.

### PR DESCRIPTION
**Pull request by bialesdaniel**
# HotFix: Wal Disabled OLTPBench Tests

## Description
This fixes #1384. The server args string was not getting created correctly. This fixes the issue with boolean server args. Also, when the DB instance starts it prints the full start command along with the arguments. 

I also took a quick pass at adding `dry-run`, it ended up being much simpler than I thought. I implemented it so that the DB server starts and prints its starting command and then stops, without doing anything. Here is the output.
```
root@2adc8c73e54d:/repo/build# python3 ../script/testing/oltpbench/run_oltpbench.py --config-file=../script/testing/oltpbench/configs/nightly/nightly_wal_disabled.json --build-type=release --dry-run
12-09-2020 17:33:08,998 [common.py:36] INFO : ****** start killing processes on port 15721 ******
12-09-2020 17:33:08,998 [common.py:36] INFO : ****** finish killing processes on port 15721 ******
12-09-2020 17:33:09,009 [db_server.py:48] INFO : Server start: /repo/build/bin/noisepage -wal_file_path=wal.log -wal_enable=false -connection_thread_count=32 -record_buffer_segment_size=1000000 [PID=4703]
12-09-2020 17:33:09,091 [db_server.py:61] INFO : DB process is verified as running in 0.68 sec
12-09-2020 17:33:09,091 [db_server.py:86] INFO : Stopped DB successfully
12-09-2020 17:33:09,649 [common.py:36] INFO : ****** start killing processes on port 15721 ******
12-09-2020 17:33:09,649 [common.py:36] INFO : ****** finish killing processes on port 15721 ******
12-09-2020 17:33:09,662 [db_server.py:48] INFO : Server start: /repo/build/bin/noisepage -wal_file_path=wal.log -wal_enable=false -connection_thread_count=32 -record_buffer_segment_size=1000000 [PID=4743]
12-09-2020 17:33:09,751 [db_server.py:61] INFO : DB process is verified as running in 0.69 sec
12-09-2020 17:33:09,751 [db_server.py:86] INFO : Stopped DB successfully
```
If you prefer it to just print the command and not even start/stop that would only be a little additional work. Let me know.

## Further work
There is some further work to improve the documentation around the testing infrastructure. We are currently working on this.

### CODE REVIEW

**Comment by lmwnshn** [comment]
> If you prefer it to just print the command and not even start/stop that would only be a little additional work. Let me know.

I think this sounds like a good idea.

**Comment by bialesdaniel** [comment]
Ok, I made it so it no longer starts the server. Also, I added a log for every time a subprocess is run (ability to skip the log cause some commands don't need to be logged like our incremental memory capture). Here is a sample of the logging during normal test execution:
```
12-09-2020 22:12:15,984 [common.py:28] INFO : Running subproccess: sudo python3 /repo/script/testing/kill_server.py 15721
12-09-2020 22:12:16,568 [common.py:39] INFO : ****** start killing processes on port 15721 ******
12-09-2020 22:12:16,568 [common.py:39] INFO : ****** finish killing processes on port 15721 ******
12-09-2020 22:12:16,578 [db_server.py:51] INFO : Server start: /repo/build/bin/noisepage -wal_file_path=wal.log -wal_enable=false -connection_thread_count=32 -record_buffer_segment_size=1000000 [PID=5242]
12-09-2020 22:12:16,666 [db_server.py:64] INFO : DB process is verified as running in 0.68 sec
12-09-2020 22:12:16,668 [common.py:28] INFO : Running subproccess: /tmp/oltpbench/oltpbenchmark -c /tmp/oltpbench/config/tatp_config.xml -b tatp --create=True --load=True
12-09-2020 22:12:17,729 [common.py:39] INFO : 22:12:17,727 (DBWorkload.java:270) INFO  - ======================================================================
12-09-2020 22:12:17,729 [common.py:39] INFO : 
12-09-2020 22:12:17,729 [common.py:39] INFO : Benchmark:     TATP {com.oltpbenchmark.benchmarks.tatp.TATPBenchmark}
12-09-2020 22:12:17,730 [common.py:39] INFO : Configuration: /tmp/oltpbench/config/tatp_config.xml
12-09-2020 22:12:17,730 [common.py:39] INFO : Type:          NOISEPAGE
12-09-2020 22:12:17,730 [common.py:39] INFO : Driver:        org.postgresql.Driver
12-09-2020 22:12:17,730 [common.py:39] INFO : URL:           jdbc:postgresql://localhost:15721/noisepage?preferQueryMode=extended
12-09-2020 22:12:17,731 [common.py:39] INFO : Isolation:     TRANSACTION_SERIALIZABLE
12-09-2020 22:12:17,731 [common.py:39] INFO : Scale Factor:  1.0
12-09-2020 22:12:17,731 [common.py:39] INFO : 
12-09-2020 22:12:17,731 [common.py:39] INFO : 22:12:17,729 (DBWorkload.java:271) INFO  - ======================================================================
12-09-2020 22:12:17,764 [common.py:39] INFO : 22:12:17,764 (DBWorkload.java:533) INFO  - Creating new TATP database...
12-09-2020 22:12:17,912 [common.py:39] INFO : 22:12:17,912 (DBWorkload.java:535) INFO  - Finished!
12-09-2020 22:12:17,912 [common.py:39] INFO : 22:12:17,912 (DBWorkload.java:536) INFO  - ======================================================================
12-09-2020 22:12:17,913 [common.py:39] INFO : 22:12:17,912 (DBWorkload.java:559) INFO  - Loading data into TATP database with 1 threads...
12-09-2020 22:12:28,834 [common.py:39] INFO : 22:12:28,833 (DBWorkload.java:563) INFO  - Finished!
12-09-2020 22:12:28,837 [common.py:39] INFO : 22:12:28,834 (DBWorkload.java:564) INFO  - ======================================================================
12-09-2020 22:12:28,837 [common.py:39] INFO : 22:12:28,837 (DBWorkload.java:598) INFO  - Skipping benchmark workload execution
12-09-2020 22:12:28,956 [common.py:28] INFO : Running subproccess: /tmp/oltpbench/oltpbenchmark -b tatp -c /tmp/oltpbench/config/tatp_config.xml -d /repo/build/oltp_result/tatp_extended_16_1.0_60_20201209-221150 --histograms --execute=True -s 5 -json-histograms /tmp/oltpbench/oltp_histograms_tatp_extended_16_1.0_60_20201209-221150.json
```
It would take more work to make it so all those commands print out but nothing happens so for the dry run I currently left it as an output like:
```
root@0e240b9a8396:/repo/build# python3 ../script/testing/oltpbench/run_oltpbench.py --config-file=../script/testing/oltpbench/configs/nightly/nightly_wal_disabled.json --build-type=release --dry-run
12-09-2020 22:18:56,474 [db_server.py:41] INFO : Server start command: /repo/build/bin/noisepage -wal_file_path=wal.log -wal_enable=false -connection_thread_count=32 -record_buffer_segment_size=1000000
12-09-2020 22:18:56,474 [db_server.py:41] INFO : Server start command: /repo/build/bin/noisepage -wal_file_path=wal.log -wal_enable=false -connection_thread_count=32 -record_buffer_segment_size=1000000
```

**Comment by bialesdaniel** [comment]
Passed the build. The code coverage stuff isn't related to my changes as far as I can tell.

**Review by lmwnshn — APPROVED** [review]
LGTM

**Pull request merged**
