### PR TITLE
Microbenchmark Test Script Metric Collection & Refactor

### PR DESCRIPTION
**Pull request by bialesdaniel**
# Microbenchmark Test Script Metric Collection & Refactor

## Summary
This commit includes the following:
- Micro_bench script can now send the results to the performance storage service
- Micro_bench script now can compare its results against artifacts in different branches or testing folders (i.e [these artifacts](http://jenkins.db.cs.cmu.edu:8080/job/testing-team/job/terrier-nightly/job/collect-microbenchmark-results/lastSuccessfulBuild/artifact/script/testing/))
- Refactor the micro_bench testing script
- Added `ant clean` step to OLTPBench test script (Should I keep this or remove it I don't think it did anything)
- Refactor some of the existing test script code for reuse and better folder structure. 
- Move the micro_bench test scripts under the `scripts/testing` folder
- Update Google Benchmark version to [1.5.2](https://github.com/google/benchmark/releases/tag/v1.5.2)
- Add script labels to Jenkinsfiles
- Update dockerfile to Ubuntu 20.04

## How to Read this PR

This PR is very large so I don't expect anyone to read the whole thing in detail.
1. It works. I have tested it in our test and staging environments. I will run it in our production environment as soon as we can merge this code https://github.com/cmu-db/noisepage-test/pull/95.
2. Low impact. If I did break this script it should only cause the nightly build to fail and it would fail after reporting the OLTPBench results
3. I think reading the description below hopefully explains a lot
4. @jazzplato has been looking more detailed into the python code
5. @apavlo If you could maybe read through the `script/testing/README.md`, the main function in `script/micro_bench/run_micro_bench.py` (just for high-level understanding which hopefully is clear from the function and variable names), and check the labels that I came up with, in the `Jenkinsfile` and `Jenkinsfile-nightly` files. 
6. @apavlo Feel free to add anyone else to the review

### Microbench updates
This PR adds the ability to report microbenchmark results to the performance storage service. The microbenchmarks will execute and as long as there were no crashes during execution all the results will be sent to the performance storage service. I added arguments for `--folders` and `--branch` which allows users to compare a run of microbenchmarks against different artifacts in Jenkins. For example, I did some of my testing with `--folders testing-team --branch  collect-microbenchmark-results`. 

In order to understand the microbenchmark codebase better, I refactored it as I went. Hopefully, I have improved the readability and modifiability of the code. I removed some dead code and refactored the classes into a folder structure that makes each component easier to understand individually. 

Also, as part of this work I upgraded the version of Google Benchmarks. I thought it gave me a feature I might want but in the end we don't want that feature and it requires implementing. The only "breaking" change in the upgrade is the way that dates are handled. I added a 2 line fix that will gracefully handle the old date format if it is encountered. 

If you want to test the microbenchmarks for yourself this is how I have been doing it. (This wont upload the results. If you want to do that you need to use the `--publish-results --publish-results-username --publish-results-password` args and I can send you the username and password. 
```bash
docker build . -t cmudb/noisepage
docker run -itd  --name build -t cmudb/noisepage
docker exec build cmake -DCMAKE_BUILD_TYPE=Release -DTERRIER_USE_ASAN=OFF -DTERRIER_USE_JEMALLOC=ON -DTERRIER_BUILD_TESTS=OFF ..
docker exec build make -j 4 terrier

# The following will compare against Jenkins and you will need to read the Readme.md to 
# comment out a line about using numactl
docker exec build python3 ../script/testing/micro_bench/run_micro_bench.py --run --benchmark-path /repo/build/release --folders testing-team --branch  collect-microbenchmark-results

# Alternatively you can do the comparison locally in which case you should run it a couple 
# of time so it generates more than one result to compare against. Also, some of the tests 
# fail on my laptop (memory issues in docker maybe) so you might want to just specify a 
# subset of the tests
docker exec build python3 ../script/testing/micro_bench/run_micro_bench.py --run --benchmark-path /repo/build/release --local
```
If you want more details about what is going on run it with `--debug`.

### Script labels
I added script labels to the Jenkins `sh` steps so that is is easier to understand what each step does. This was prompted by the fact that the OLTPBench tests all just showed up as `Shell script`. Here is an example of what it looks like http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/44/pipeline/118. I didn't label everything because some things didn't feel like they needed labels and I wasn't sure what some things were doing. If you think there should be different labels just let me know or push an update. 

## Remaining tasks

- [x] This PR is dependant on https://github.com/cmu-db/noisepage-test/pull/95
- [x] https://github.com/cmu-db/noisepage-test/pull/95 is waiting on Slack Webhook

## Further work

- I deprecated the `--csv-dump` command. It would not be difficult to add this back in if it would be helpful.
- At some point, we could use results stored in TimescaleDB for the comparison. This would remove the dependency on storing Jenkins artifacts, but this is currently not a planned effort.

### CODE REVIEW

**Comment by bialesdaniel** [comment]
I will be posting passing Jenkins builds from the testing-team folders as soon as the dependant PRs in other repos have been merged and I can run them.

**Comment by bialesdaniel** [comment]
Passing Terrier Pipeline: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/49/pipeline/156
Passing Nightly Pipeline: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/collect-microbenchmark-results/73/pipeline/27
There is no data in the `ref throughput | %tolerance | %change | %coef var | ref type | #results` because there are no historical results to compare against.

**Comment by bialesdaniel** [comment]
Update build results with all the merges: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/71/pipeline/500

**Comment by bialesdaniel** [comment]
Most recent passing build: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/76/pipeline/

**Review by apavlo — APPROVED** [review]
This looks like a logical refactor of the previous monolithic script. I'm okay with these changes.

Stupid Request: Since you are already making major changes, can you rename `micro_bench` to `microbench`.

**Comment by bialesdaniel** [comment]
Ok I made that change. I'll run it through Jenkins once more to double check. Then I think we will be good to merge

**Comment by bialesdaniel** [comment]
Latest passing nightly: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/collect-microbenchmark-results/89/pipeline
Latest passing terrier: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/79/pipeline/140

**Pull request merged**
